# Generated by Django 4.0.3 on 2022-04-25 11:06

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('item', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('is_admin', models.IntegerField()),
                ('confirm_password', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('Category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.category')),
            ],
            options={
                'db_table': 'Sub_Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL')], max_length=200)),
                ('colors', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Black'), ('2', 'Blue'), ('3', 'Red'), ('4', 'White'), ('5', 'Yellow'), ('6', 'Green'), ('7', 'Gray')], max_length=200)),
                ('sub_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.sub_category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('gal_id', models.AutoField(primary_key=True, serialize=False)),
                ('gal_image', models.FileField(upload_to='')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.product')),
            ],
        ),
    ]
