# Generated by Django 4.0.3 on 2022-04-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customer',
        ),
    ]
