# Generated by Django 4.0.3 on 2022-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
    ]
